stages:
- test
- build

.test:
  script:
    - pip install -r requirements.txt
    - pip install pylint --quiet
    - pylint --ignored-classes=_socketobject *.py

python-3.4:
  extends: ".test"
  stage: test
  image: python:3.4

python-3.5:
  extends: ".test"
  stage: test
  image: python:3.5

python-3.6:
  extends: ".test"
  stage: test
  image: python:3.6

python-3.7:
  extends: ".test"
  stage: test
  image: python:3.7

build:
  image: python:3.6
  stage: build
  script:
    - pip install -U setuptools
    - python setup.py
