stages:
- test
- deploy_stage
- test_stage
- deploy_prod

.test:
  script:
    - pip install -r requirements.txt
    - pip install pylint --quiet
    - pylint --ignored-classes=_socketobject ./python-ddns/python-ddns.py

python-3.4:
  extends: ".test"
  stage: test
  image: python:3.4

python-3.5:
  extends: ".test"
  stage: test
  image: python:3.5

python-3.6:
  extends: ".test"
  stage: test
  image: python:3.6

python-3.7:
  extends: ".test"
  stage: test
  image: python:3.7

deploy_staging:
 # expect:tags
  stage: deploy_stage
  image: python:3.6
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
  script:
    - pip install -U setuptools twine
    - python setup.py sdist bdist_wheel
    - python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*

test_stage:
  stage: test_stage
  image: python:3.6
  script:
    - pip install --index-url https://test.pypi.org/simple/ python-ddns
  

deploy_production:
  stage: deploy_prod
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - twine upload dist/*
  only:
    - tags
  when: manual