stages:
- test
- deploy_stage
- test_stage
- deploy_prod

include:
  - template: Dependency-Scanning.gitlab-ci.yml

.test:
  script:
    - pip install -r requirements.txt
    - pip install pylint --quiet
    - pylint --ignored-classes=_socketobject ./python_ddns/python_ddns.py

python-3.4:
  extends: ".test"
  stage: test
  image: python:3.4

python-3.5:
  extends: ".test"
  stage: test
  image: python:3.5

python-3.6:
  extends: ".test"
  stage: test
  image: python:3.6

python-3.7:
  extends: ".test"
  stage: test
  image: python:3.7

Staging:
  artifacts:
     paths:
     - dist/Python_DDNS*.whl
  stage: deploy_stage
  image: python:3.6
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
  script:
    - pip install -U setuptools twine --quiet
    - python setup.py sdist bdist_wheel
    - python -m twine check dist/*

test_stage:
  stage: test_stage
  image: python:3.6
  script:
    - pip install dist/*.whl
    - pip show -f python-ddns
    - command -v python-ddns
    - python-ddns -t
  

deploy_production:
  image: python:3.6
  stage: deploy_prod
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - pip install -U setuptools twine --quiet
    - python setup.py sdist bdist_wheel
    - python -m twine check dist/*
    - python -m twine upload dist/*
  only:
    refs:
      - tags
      - master
    variables:
      - $CI_COMMIT_TAG