stages:
- lint
- test
- Build
- Test_Build
- Deploy_to_PyPi

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml

.lint:
  before_script:
    - pip install -U pip pylint flake8 requests
  script:
    - pylint ./pddns -r y
    - flake8 ./pddns

python-3.5:
  extends: ".lint"
  stage: lint
  image: python:3.5

python-3.6:
  extends: ".lint"
  stage: lint
  image: python:3.6

python-3.7:
  extends: ".lint"
  stage: lint
  image: python:3.7

python-3.8:
  extends: ".lint"
  stage: lint
  image: python:3.8

Build:
  artifacts:
     paths:
     - dist/
  stage: Build
  image: python:3.6
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
  script:
    - pip install -U setuptools twine --quiet
    - python setup.py sdist bdist_wheel
    - python -m twine check dist/*
  except:
    - tags

Test_Build:
  stage: Test_Build
  image: python:3.6
  script:
    - pip install dist/*.whl
    - pip show -f python-ddns
    - command -v pddns
    - pddns -i -d
    - pddns -t -d
  except:
    - tags


Deploy_to_PyPi:
  image: python:3.6
  stage: Deploy_to_PyPi
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - pip install -U setuptools twine --quiet
    - python setup.py sdist bdist_wheel
    - python -m twine check dist/*
    - python -m twine upload dist/*
  only:
    refs:
      - tags
      - master
    variables:
      - $CI_COMMIT_TAG