language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current detault Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pylint
# command to run tests
script:
  - pylint --ignored-classes=_socketobject python-ddns.py